---
version: "3.7"

name: bjj-graph

services:
  app:
    container_name: bjj-graph_app
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/code
  db:
    container_name: bjj-graph_db
    image: neo4j:5.9.0
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    # env_file:
    #   - .env
    volumes:
      - dbdata:/data/
    ports:
      - 7474:7474
      - 7687:7687

volumes:
  dbdata:
    driver: local
